### ISSUE TITLE
runVaccination and saveLoadFunctions modules missing

### ISSUE THREAD

**Issue by Yaroslav00** [lulelita/one_vs_two_doses#2]
Hi, I am interested in your article for educational purposes and I want to reproduce your code. It seems that two modules are missing including quite an important one (runVaccination.py or smth like that). Could you please upload it or give some intuition about what it contains?
Thanks in advance

**Comment by laura-matrajt** [comment]
just added it

**Comment by Yaroslav00** [comment]
Thanks!
